# Generated by Django 3.1.1 on 2020-09-10 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=200)),
                ('weight', models.IntegerField(default=0)),
                ('acres', models.IntegerField(default=0)),
                ('amount_Nitrate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_Phosphate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_Potassium', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_Ammonium', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_Calcium', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoilAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ph_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.fertilizer')),
            ],
        ),
    ]
