# Generated by Django 3.1.1 on 2020-09-30 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farm_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farminput',
            name='fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.fertilizer'),
        ),
    ]
