# Generated by Django 3.1.1 on 2020-10-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farms',
            field=models.ManyToManyField(related_name='farmer_farms', to='calculator.Farm'),
        ),
    ]
