# Generated by Django 3.1.1 on 2020-10-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20201002_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farmer',
            new_name='farm_owner',
        ),
    ]
