# Generated by Django 3.1.1 on 2020-10-02 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0003_auto_20201002_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farm_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_farmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farms',
            field=models.ManyToManyField(related_name='farmers_farms', to='calculator.Farm'),
        ),
    ]
