# Generated by Django 3.1.1 on 2020-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20201002_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farms',
            field=models.ManyToManyField(related_name='farmer_farms', to='calculator.Farm'),
        ),
    ]
