# Generated by Django 3.1.1 on 2020-09-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20200926_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertilizeravailable',
            options={'verbose_name_plural': 'Fertilizers available'},
        ),
    ]
